# Generated by Django 6.0.4 on 2026-04-27 02:31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'گزارش', 'verbose_name_plural': 'گزارش\u200cها'},
        ),
        migrations.AddField(
            model_name='report',
            name='nlp_category_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='ضریب اطمینان NLP'),
        ),
        migrations.AddField(
            model_name='report',
            name='nlp_meta',
            field=models.JSONField(blank=True, help_text='نتیجه خودکار تحلیل هوش مصنوعی شامل: دسته\u200cبندی، امتیاز بحران، احساسات', null=True, verbose_name='متادیتای NLP'),
        ),
        migrations.AddField(
            model_name='report',
            name='nlp_suggested_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nlp_suggested_reports', to='reports.category', verbose_name='دسته پیشنهادی NLP'),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='report',
            name='image_after',
            field=models.ImageField(blank=True, null=True, upload_to='reports/after/', verbose_name='تصویر بعد'),
        ),
        migrations.AlterField(
            model_name='report',
            name='image_before',
            field=models.ImageField(upload_to='reports/before/', verbose_name='تصویر قبل'),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='فوری'),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='موقعیت مکانی'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'ثبت شده'), ('UNDER_REVIEW', 'در حال بررسی'), ('ASSIGNED', 'ارجاع داده\u200cشده'), ('IN_PROGRESS', 'در حال اقدام'), ('RESOLVED', 'حل\u200cشده'), ('CLOSED', 'مختومه')], default='SUBMITTED', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
