# Generated by Django 6.0.4 on 2026-04-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_category_options_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='nlp_meta',
            field=models.JSONField(blank=True, null=True, verbose_name='متادیتای NLP'),
        ),
    ]
